### ISSUE TITLE
About the training and testing.

### ISSUE THREAD

**Issue by Uni-Summer** [nihaomiao/MICCAI22_ADN#1]
That is a promising job. Will the complete process of training and testing be released soon?
Thanks!

**Comment by nihaomiao** [comment]
Hi, @Uni-Summer, thanks very much for your interest! I am busy with some projects recently. I will gradually release the complete process of training and testing when I have time. 

Bests
Haomiao

**Comment by nihaomiao** [comment]
Code released.
