### ISSUE TITLE
About dice metrics

### ISSUE THREAD

**Issue by JiaRuiS** [nihaomiao/MICCAI22_ADN#2]
May I ask whether the dice evaluation metrics of the paper is dice per case or global dice?

**Comment by nihaomiao** [comment]
Hi, @JiaRuiS, thanks for your interest! We compute volume-based dice for each scan and then report the average of them.

**Comment by JiaRuiS** [comment]
Thanks for your prompt answer. I would like to ask when you are testing the dataset, is the size of each test data and label also 40*256*256?

**Comment by nihaomiao** [comment]
Yes, as mentioned in our paper, "after skull stripping, we resample all NCCTs to be 1.2 × 1.2 × 5 mm^3 and reshape
them to be 256×256×40 using the Python package nilearn."

**Comment by JiaRuiS** [comment]
Thanks for your patience and detailed answer！
