### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by jianjun0407** [nihaomiao/MICCAI22_ADN#3]
First of all, thank you for sharing. I have been reproducing your paper and code recently, and I have some questions to ask you.
(1)The first Network I trained, Transformation Network T, used NVIDIA 3060  for one day, but the result was not very good. May I ask how long have you trained this network?

(2)For the mask in the AISD dataset, is it to use all 1,2,3,5 in the label as labels of the lesion area?
(3)Could you share the model parameters(checkpoint) of the three networks you trained T, D and F, so as to directly test the segmentation effect on the ncct images ?

**Comment by jianjun0407** [comment]
![Tresult](https://user-images.githubusercontent.com/19251556/225193478-99f2b0bb-203b-403b-9e65-b1172da8ea40.PNG)
The test results of the T network

**Comment by nihaomiao** [comment]
Hi, @jianjun0407,

Thanks very much for your interest in our work! Please see my answer to your questions as follows:

(1) It should not be long to train the T network. From the test results you show, it seems that you don't use skull-strip? The input to ADN should be preprocessed with skull-strip and denoising. You can check the figures shown in our paper. The NCCTs after preprocessing should look like them. 

(2) Yes

(3) The input NCCTs used for training our networks are preprocessed by our collaborated doctors with some off-the-shelf tools. They may not work well for those inputs using different pre-processing ways. I suggest you preprocess the NCCTs and directly retrain the models. But if you still think our model parameters will help, I can send them to your email.

**Comment by jianjun0407** [comment]
Thank you for your quick reply!
Indeed, I did not remove the skull from the image. I'm going to change that. 
In addition, I have a question about why the Transformation Network training with non-skull images has such a big impact on the results.

**Comment by nihaomiao** [comment]
Hi, the intuition of the T network is that, if the NCCT is quasi-symmetric, it should have the minimum difference from its horizontally-flipped version. These surrounding skulls will adversely affect the transformation. You may also refer to our paper for more details about this part. Thanks!

**Comment by jianjun0407** [comment]
The difference in image preprocessing does have a large impact on the results. 
If possible, I plan to use my preprocessing method (skull removal must be added) based on your parameters for retrain, so that it will be more stable. My email is jianjun5277@163.com, thank you for sharing !
Thank you for your reply and look forward to further communication with you about the effect of the algorithm

**Comment by nihaomiao** [comment]
Sure! I will send our pre-trained models to you this week. Thanks again for your interest in our work!
