### ISSUE TITLE
Checkpoint of the brain tissue segmentation network

### ISSUE THREAD

**Issue by yimuu** [nihaomiao/MICCAI22_ADN#5]
Could you please provide the checkpoint of the brain tissue segmentation network(‘’gwm_seg_model‘’) ?

**Comment by nihaomiao** [comment]
Hi, @yimuu, sorry for the late reply! Please refer to this [link](https://drive.google.com/file/d/1T0LxD8zxRZzWSkyKKYvkIhz84_IdkyU4/view?usp=drive_link). But note that our model is trained on pre-processed data. The doctors used MATLAB to perform skull-stripping and denoising for pre-processing. And the GWM labels are generated by SPM12 through MATLAB. We then use the labels to train this auxiliary GWM segmentation model.
