### ISSUE TITLE
puzzeled

### ISSUE THREAD

**Issue by GitHub-TXZ** [nihaomiao/MICCAI22_ADN#7]
I'm sorry to bother you again. I downloaded SPM12 and would like to inquire about the specific details of skull dissection and GWM segmentation. Is your GWM segmented using the NII.gz file from CT?

**Comment by nihaomiao** [comment]
Hi, @GitHub-TXZ, I did not know how doctors processed data with MATLAB. But I asked them before and they showed me this GitHub [link](https://github.com/neurolabusc/Clinical). It may help you to perform GWM segmentation. For the data preprocessing, you can just follow your own way and may use [our provided models](https://drive.google.com/drive/folders/198JNeouZdOLo__wVe30KXaiS1ScwaOTn) to accelerate your training. Please feel free to let me know if you have more questions.

**Comment by GitHub-TXZ** [comment]
The link you provided is for image standardization and does not have the function of removing skull and extracting GM, WM, and CSF. In addition, the number of slices in DWI and CT of the AISD dataset you know is not entirely consistent. This means that we cannot use MRI to remove the skull. However, the current algorithm mainly focuses on MRI skull removal, and the SPM12 I know of cannot meet the requirements of the razor in your paper

**Comment by GitHub-TXZ** [comment]
> 

I have now used advanced algorithms from others' papers to peel off the skull. In your paper, you mentioned using SPM12 to segment CT brain images into CSF, WM, and GM. But to my knowledge, the segmentation of SPM12 is based on MRI. I would like to ask how you segmented these three brain tissue structures based on SPM12. In addition, I used FSL for segmentation myself, but since FSL is also based on MRI analysis, the segmentation effect is very poor. How should I continue to advance? I look forward to your answer.

**Comment by nihaomiao** [comment]
Hi, @GitHub-TXZ, could you just try SPM12 to see whether you can get some reasonable results?  Also, you can also consider trying our method without using the tissue segmentation results, as shown in Table 1.

**Comment by GitHub-TXZ** [comment]
I tested using your checkpoint and the results were very poor (many false positive voxels). My preprocessing: Use SImpleITK padding to 40 slices, and then resize it online in your dataloader. Can you provide the preprocessed code (how to unify them into 256256,40), or directly provide the preprocessed AISD dataset? Thank you!

**Comment by GitHub-TXZ** [comment]
![Uploading Snipaste_2023-08-12_18-43-54.png…]()

**Comment by GitHub-TXZ** [comment]
![Snipaste_2023-08-12_18-43-54](https://github.com/nihaomiao/MICCAI22_ADN/assets/73587759/5743d2c6-3889-4ec3-af52-f6ead033cfd8)

**Comment by GitHub-TXZ** [comment]
Can you answer my related questions? Thank you very much!

**Comment by nihaomiao** [comment]
Hi, @GitHub-TXZ, I think that I have answered most of your questions before, e.g., in your previous [issue](https://github.com/nihaomiao/MICCAI22_ADN/issues/6#issuecomment-1649804285). You may also check my answer in other issues.
